import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import { Context } from "../store/store";

import Logo from "../assets/logo.png";

import styles from "../styles/pages/publications.module.scss";

const Publications = () => {
  const { store, actions } = useContext(Context);
  return (
    <>
      <Head>
        <title>Publications | Gonzalo Díaz Cobacho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.h1}>Publications</h1>
      </main>
    </>
  );
};

export default Publications;
