import Head from "next/head";

import CardsSection from "../components/Publications/CardsSection";
import ConferencesSection from "../components/Publications/Conferences/ConferencesSection";
import Pills from "../components/Publications/Pills";

import { useContext, useEffect } from "react";
import { Context } from "../store/store";

import styles from "../styles/pages/publications.module.scss";

const Publications = () => {
  const { store, actions } = useContext(Context);

  return (
    <>
      <Head>
        <title>Publications | Gonzalo Díaz Cobacho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} ${store.fadeCurrent ? styles.mainFade : ""}`}
      >
        <div className={styles.container}>
          <h1 className={styles.h1}>Publications</h1>
          <h1 className={styles.h1Sub}>and Conferences</h1>
          <Pills />
          {store.showPublications ? <CardsSection /> : <ConferencesSection />}
        </div>
      </main>
    </>
  );
};

export default Publications;
